on: [push, pull_request]
name: Continuous Integration

jobs:
  build-android:
    name: Build Android
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 11

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore .NET workloads
        run: dotnet workload install android

      - name: Get .NET Info
        run: dotnet --info

      - name: List sdk-manifests
        run: ls "C:\Program Files\dotnet\sdk-manifests"

      - name: Compile
        run: dotnet build -c Debug AndroidApp/AndroidApp.sln
